In [1]:
# Tensors
# Basic building block

import torch
import numpy as np

In [30]:
scalar = torch.tensor(12.1)
print(f"scalar value: {scalar:>.2f}")

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

print(x_data)
print(type(x_data))

scalar value: 12.10
tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>


In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

print(np_array)
print(x_np)
print(type(x_np))

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>


In [4]:
# tensor data is reference of the numpy array. not copied
np_array[1, 1] = 1

print(np_array)
print(x_np)

[[1 2]
 [3 1]]
tensor([[1, 2],
        [3, 1]])


In [5]:
x_ones = torch.ones_like(x_data)  # x_data is tensor
x_rand = torch.rand_like(x_data, dtype=torch.float)

print(x_ones)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.2348, 0.4360],
        [0.2825, 0.0781]])


In [6]:
# from shape
rand_tensor = torch.rand(2, 3)
ones_tensor = torch.ones((3, 2)) # 3x2 matrix
zeros_tensor = torch.zeros(5)  # row vector

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.0107, 0.0151, 0.4756],
        [0.7289, 0.2233, 0.4001]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([0., 0., 0., 0., 0.])


In [23]:
# with numpy
np_rand = rand_tensor.numpy()
print(np_rand)
print(type(np_rand))

# change tensor elements
rand_tensor.add_(0.1)
# reflects to the numpy array
print(np_rand)

[[0.11074231 0.1150556  0.5756198 ]
 [0.8289369  0.323297   0.5001325 ]]
<class 'numpy.ndarray'>
[[0.21074231 0.2150556  0.67561984]
 [0.9289369  0.423297   0.6001325 ]]


In [7]:
# tensors' device
print(f"x_data's default device: {x_data.device}")
if torch.cuda.is_available():
    print("cuda device is available")
    x_data = x_data.to("cuda")
print(f"x_data's changed device: {x_data.device}")

x_data's default device: cpu
cuda device is available
x_data's changed device: cuda:0


In [10]:
# slicing tensor

# tensor[row,col]
print(ones_tensor[0,:])
print(rand_tensor[:,1])
print(rand_tensor[1])

tensor([1., 1.])
tensor([0.0151, 0.2233])
tensor([0.7289, 0.2233, 0.4001])


In [12]:
# matrix multiplication
y1 = rand_tensor @ ones_tensor
y2 = ones_tensor.matmul(rand_tensor)

print(y1)
print(y2)

tensor([[0.5014, 0.5014],
        [1.3524, 1.3524]])
tensor([[0.7397, 0.2384, 0.8758],
        [0.7397, 0.2384, 0.8758],
        [0.7397, 0.2384, 0.8758]])


In [13]:
# element wise multiplication (error)
y1 = rand_tensor * ones_tensor
y2 = ones_tensor.mul(rand_tensor)

print(y1)
print(y2)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [15]:
# element wise multiplication (error)
y1 = rand_tensor * rand_tensor
y2 = rand_tensor.mul(rand_tensor)
print(y1)
print(y2)

tensor([[1.1540e-04, 2.2667e-04, 2.2621e-01],
        [5.3135e-01, 4.9862e-02, 1.6011e-01]])
tensor([[1.1540e-04, 2.2667e-04, 2.2621e-01],
        [5.3135e-01, 4.9862e-02, 1.6011e-01]])


In [19]:
agg = ones_tensor.sum()
agg_item = agg.item()
print(agg_item)
print(agg.shape)
print(type(agg))
print(type(agg_item))

6.0
torch.Size([])
<class 'torch.Tensor'>
<class 'float'>


In [20]:
# in-place operation
ones_tensor.add_(2)
print(ones_tensor)

tensor([[3., 3.],
        [3., 3.],
        [3., 3.]])


In [34]:
float_16_tensor = torch.rand(size=(2, 3), dtype=torch.float16)
float_32_tensor = torch.rand(size=(2, 3), dtype=torch.float32)

z1 = float_16_tensor * float_32_tensor
print(z1)
print(z1.dtype)

tensor([[0.1670, 0.4094, 0.0658],
        [0.3727, 0.0372, 0.2568]])
torch.float32


In [36]:
# errror case
float_16_tensor = torch.rand(size=(2, 3), dtype=torch.float16)
float_32_tensor = torch.rand(size=(2, 3), device="cuda:0", dtype=torch.float32)

z1 = float_16_tensor * float_32_tensor
print(z1)
print(z1.dtype)

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [38]:
print(rand_tensor)

# min/max
print(rand_tensor.min())
print(rand_tensor.max())

# Positional min/max
print(rand_tensor.argmin())
print(rand_tensor.argmax())

tensor([[0.2107, 0.2151, 0.6756],
        [0.9289, 0.4233, 0.6001]])
tensor(0.2107)
tensor(0.9289)
tensor(0)
tensor(3)


In [45]:
# reshape
x = torch.arange(1, 8, dtype=torch.float32)
print(x.shape)
print(x)

x_reshaped = x.reshape(7, 1)
print(x_reshaped.shape)
print(x_reshaped)

# original tensor is not changed
print(x)

tensor([1., 2., 3., 4., 5., 6., 7.])
torch.Size([7])
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.]])
torch.Size([7, 1])
tensor([1., 2., 3., 4., 5., 6., 7.])


In [53]:
# stack
x_stacked = torch.stack([x, x, x], dim=0)
print(x_stacked)

x_stacked = torch.stack([x, x, x], dim=1)
print(x_stacked)

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])
tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.]])


In [54]:
# tensor on gpu to numpy?
gpu_tensor = torch.rand(5, device="cuda")
print(gpu_tensor)

np_gpu_array = gpu_tensor.numpy()
print(np_gpu_array)

tensor([0.3049, 0.4399, 0.2331, 0.0420, 0.8369], device='cuda:0')


TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [55]:
# so,
np_cpu_array = gpu_tensor.cpu().numpy()
print(np_cpu_array)

[0.3049381  0.43990096 0.23314981 0.04202771 0.8368703 ]
